/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import models.Account;
import models.ButtonColumn;
import db_connection.DBAccess;
import models.UserImages;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import models.OperationJson;
import utils.BaseURL;
import utils.EncodeDecode;

/**
 *
 * @author dell
 */
public class frmLoadImageData extends javax.swing.JFrame {
    private static Account acc;
    private List<UserImages> userImages;
    private ButtonColumn buttonColumn;
    private final Gson gson;
    /**
     * Creates new form frmLoadImageData
     * @param acc
     */
    public frmLoadImageData(Account acc) {
        initComponents();
        frmLoadImageData.acc = acc;
        gson=new Gson();
        loadImage();
        renderButtonDelete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbImage = new javax.swing.JTable();
        btnTroVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbImage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã người dùng", "Mã ảnh", "Ảnh", "Xoá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbImage);

        btnTroVe.setText("Trở về");
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTroVe)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnTroVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        // TODO add your handling code here:
        frmInfo open = new frmInfo(acc);
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTroVeActionPerformed
    
    private void loadImage() {
        try {
            Socket socket = new Socket(BaseURL.SERVER_ADDRESS, BaseURL.PORT);
            
            // Khởi tạo InputStream và output Stream để giao tiếp với server
            BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
            OperationJson sendJson=new OperationJson();
            sendJson.setOperation("load-image/"+acc.getID_User());
            System.out.println("AccountID:::::"+acc.getID_User());
            out.println(gson.toJson(sendJson));
            String fromServer=in.readLine();
            OperationJson result=gson.fromJson(fromServer, OperationJson.class);
            if(result.getOperation().equals("Success")){
                String listImagesJson=EncodeDecode.decodeBase64FromJson(result.getData().toString());
                userImages = gson.fromJson(listImagesJson, new TypeToken<List<UserImages>>() {}.getType());
//                        access.getUserImage(acc.getID_User());
                DefaultTableModel model = (DefaultTableModel) tbImage.getModel();
                model.setRowCount(0);
                for (UserImages image : userImages) {
                    String userID = image.getID_User();
                    String imageID = image.getID_Image();
                    byte[] imageData = image.getImages();
                    ImageIcon imageIcon = new ImageIcon(imageData);
                    Image scaledImage = imageIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                    ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
                    model.addRow(new Object[]{userID, imageID, scaledImageIcon});
                }
                // Set the custom cell renderer for the image column
                TableColumn imageColumn = tbImage.getColumnModel().getColumn(2);
                imageColumn.setCellRenderer(new ImageRenderer());
                tbImage.setRowHeight(100);
            }
            else{
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra!","Lỗi",0);
            }
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(frmLoadImageData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void renderButtonDelete(){       
        clickLastColumnCell();
        Icon deleteIcon = new  ImageIcon("src\\icons\\delete.png");
        buttonColumn = new ButtonColumn(tbImage, tbImage.getColumnCount() - 1,deleteIcon);
    }
    
    private void clickLastColumnCell(){
        
        tbImage.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tbImage.rowAtPoint(e.getPoint());
                int column = tbImage.columnAtPoint(e.getPoint());
                if (column == tbImage.getColumnCount() - 1) {
                    
                    int selectedRow = tbImage.convertRowIndexToModel(row);
                    Object idImage = tbImage.getModel().getValueAt(selectedRow, 1);
                    int result = JOptionPane.showConfirmDialog(
                            null,
                            "Bạn có chắc muốn xoá ảnh này này? ",
                            "Xác nhận",
                            JOptionPane.YES_NO_OPTION);

                    if (result == JOptionPane.YES_OPTION)
                    {
//                        if(access.deleteUserImage(idImage.toString())){
//                            JOptionPane.showMessageDialog(null, "Đã xoá ảnh");
//                            loadImage();
//                        }  
                    }
                    else
                        return;
                
                }

            }
        });
    }

    // Custom cell renderer to display the image
    class ImageRenderer extends JLabel implements TableCellRenderer {
        public ImageRenderer() {
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setIcon((Icon) value);
            return this;
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoadImageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoadImageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoadImageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoadImageData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoadImageData(acc).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTroVe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbImage;
    // End of variables declaration//GEN-END:variables
}
