/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import facial_recognition.FaceReconigtion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import routes.FormRoute;


/**
 *
 * @author dell
 */
public class frmRecognition extends javax.swing.JFrame {

    private Thread thread;
    private byte[] imageChoose;
    private FaceReconigtion face;
    
    private int originalWidth; 



        /**
     * Creates new form frmRecognitionTest
     */
    public frmRecognition() {
         initComponents(); 
        txtTiLe.setEnabled(false);
        face = new FaceReconigtion();
        face.getAccountInfoLabel(frmRecognition.this,lbName, lbBirthDay, lbAddress, lbPhone, lbGender, lbEmail,pnAccountInfo);
        face.storeOriginalWidth();
        face.getDisplayDetectValue(lblFaceCapture, lblDataFace, txtTiLe);
        pnAccountInfo.setVisible(false);
        face.setMode(false);
        
        runableThread();
        getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.cyan)); 
    }

    private void runableThread(){
        Runnable frameGrabber = () -> {
                while (true) {
                    face.initializeCamera("Nhận diện", lblDisplayCapture);
                }
            };
            // Create a new thread for grabbing frames from the camera
            thread = new Thread(frameGrabber); 
            thread.setDaemon(true);  
            thread.start();   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcChooseImage = new javax.swing.JFileChooser();
        pnAccountInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbBirthDay = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnRecognition = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnMoCamera = new javax.swing.JButton();
        btnNhanDien = new javax.swing.JButton();
        btnChonAnh = new javax.swing.JButton();
        lblDisplayCapture = new javax.swing.JLabel();
        lblDataFace = new javax.swing.JLabel();
        lblFaceCapture = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTiLe = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        pnBackGroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhận diện khuôn mặt");
        setResizable(false);

        pnAccountInfo.setBackground(new java.awt.Color(204, 204, 204));
        pnAccountInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel2.setText("Thông tin tài khoản");
        pnAccountInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, 38));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setText("Họ tên");
        pnAccountInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, -1));

        lbName.setBackground(new java.awt.Color(255, 255, 255));
        lbName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbName.setOpaque(true);
        pnAccountInfo.add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, 20));

        lbBirthDay.setBackground(new java.awt.Color(255, 255, 255));
        lbBirthDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbBirthDay.setOpaque(true);
        pnAccountInfo.add(lbBirthDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 230, 20));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setText("Ngày sinh");
        pnAccountInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, -1));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel9.setText("Giới tính");
        pnAccountInfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, -1));

        lbGender.setBackground(new java.awt.Color(255, 255, 255));
        lbGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbGender.setOpaque(true);
        pnAccountInfo.add(lbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 230, 20));

        lbPhone.setBackground(new java.awt.Color(255, 255, 255));
        lbPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPhone.setOpaque(true);
        pnAccountInfo.add(lbPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 230, 20));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel12.setText("SDT");
        pnAccountInfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 75, 20));

        lbEmail.setBackground(new java.awt.Color(255, 255, 255));
        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEmail.setOpaque(true);
        pnAccountInfo.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 230, 20));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel14.setText("Email");
        pnAccountInfo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 75, 20));

        lbAddress.setBackground(new java.awt.Color(255, 255, 255));
        lbAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAddress.setOpaque(true);
        pnAccountInfo.add(lbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 230, 20));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel16.setText("Địa chỉ");
        pnAccountInfo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 75, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.png"))); // NOI18N
        pnAccountInfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 70));

        pnRecognition.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRefresh.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reset.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        pnRecognition.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 170, 50));

        btnMoCamera.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnMoCamera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/camera.png"))); // NOI18N
        btnMoCamera.setText("Mở camera");
        btnMoCamera.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMoCamera.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMoCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoCameraActionPerformed(evt);
            }
        });
        pnRecognition.add(btnMoCamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 180, 50));

        btnNhanDien.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnNhanDien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/face-scan.png"))); // NOI18N
        btnNhanDien.setText("Nhận diện");
        btnNhanDien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnNhanDien.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNhanDien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanDienActionPerformed(evt);
            }
        });
        pnRecognition.add(btnNhanDien, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 170, 50));

        btnChonAnh.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gallery.png"))); // NOI18N
        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnChonAnh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });
        pnRecognition.add(btnChonAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 180, 50));
        pnRecognition.add(lblDisplayCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 730, 450));
        pnRecognition.add(lblDataFace, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 300, 280));
        pnRecognition.add(lblFaceCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 300, 260));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Tỉ lệ giống: ");
        pnRecognition.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));
        pnRecognition.add(txtTiLe, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 322, 71, 30));

        btnReturn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/return.png"))); // NOI18N
        btnReturn.setText("Trở về");
        btnReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        pnRecognition.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        pnBackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        pnRecognition.add(pnBackGroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnRecognition, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRecognition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnAccountInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoCameraActionPerformed
        // TODO add your handling code here:
        if (face.isIsRecording()) {
            // Stop recording
            face.setIsRecording(false);
            btnMoCamera.setText("Mở camera");
        } else {
            // Start recording
            face.setIsRecording(true);
            btnMoCamera.setText("Tắt camera");
        }
    }//GEN-LAST:event_btnMoCameraActionPerformed

    private void btnNhanDienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanDienActionPerformed
        // TODO add your handling code here:
        if(!face.isIsRecording() && imageChoose == null){
            JOptionPane.showMessageDialog(null, "Chưa chọn ảnh hoặc bật camera");
            return;
        }
        if(imageChoose != null){
            face.setImageChoose(imageChoose);   
            if(!face.isIsRecording())
                face.facialRecognition(imageChoose);            
            imageChoose = null;
        }    
        
        if(!face.isCheck()){                       
            face.setCheck(true);   
        }
        
    }//GEN-LAST:event_btnNhanDienActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        // TODO add your handling code here:
        JFileChooser fcImageChoose = new JFileChooser();
        fcImageChoose.setVisible(true);
        fcImageChoose.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // Set file filter to allow only image files
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif");
        fcImageChoose.setFileFilter(imageFilter);

        if (fcImageChoose.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fcImageChoose.getSelectedFile();
                Path imagePath = selectedFile.toPath();
                byte[] imageBytes = Files.readAllBytes(imagePath);  
                byte[] faceImage = face.detctFace(imageBytes);
                if(faceImage != null){           
                    InputStream inputStream = new ByteArrayInputStream(faceImage );
                    BufferedImage imageBuffer1 = ImageIO.read(inputStream);
                    ImageIcon icon1 = new ImageIcon(imageBuffer1);
                    lblFaceCapture.setIcon(icon1);    
                    imageChoose = imageBytes;   
                }
                else{
                    JOptionPane.showMessageDialog(null, "Không tìm thấy khuôn mặt trong ảnh chọn");
                }
            } catch (HeadlessException | IOException ex) {
                JOptionPane.showConfirmDialog(null, ex);
            }
        }        
    }//GEN-LAST:event_btnChonAnhActionPerformed
    
    
   
    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        face.setIsRecording(false);
        FormRoute.openFormLogin(this);
    }//GEN-LAST:event_btnReturnActionPerformed
    
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        face.setCheck(false);
        face.setIsRecording(false);
        FormRoute.openFormRecognitionTest(this);
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecognition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecognition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecognition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecognition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecognition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnMoCamera;
    private javax.swing.JButton btnNhanDien;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReturn;
    private javax.swing.JFileChooser fcChooseImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbBirthDay;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lblDataFace;
    private javax.swing.JLabel lblDisplayCapture;
    private javax.swing.JLabel lblFaceCapture;
    private javax.swing.JPanel pnAccountInfo;
    private javax.swing.JLabel pnBackGroundImage;
    private javax.swing.JPanel pnRecognition;
    private javax.swing.JTextField txtTiLe;
    // End of variables declaration//GEN-END:variables
}
