/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import facial_recognition.FaceReconigtion;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author dell
 */
public class frmRecognitionTest extends javax.swing.JFrame {

    private Thread thread;
    private byte[] imageChoose;
    private FaceReconigtion face;
    
    private int originalWidth; 



        /**
     * Creates new form frmRecognitionTest
     */
    public frmRecognitionTest() {
        
       
        
        // Calculate the new image dimensions to fit the frame
         initComponents(); 

//        extendForm(isExtended);
        txtTiLe.setEnabled(false);
        face = new FaceReconigtion();
        face.getAccountInfoLabel(frmRecognitionTest.this,lbName, lbBirthDay, lbAddress, lbPhone, lbGender, lbEmail,pnAccountInfo);
        face.storeOriginalWidth();
        face.getDisplayDetectValue(lblFaceCapture, lblDataFace, txtTiLe);
        pnAccountInfo.setVisible(false);
        face.setMode(false);
        
        runableThread();
    }
//    private void storeOriginalWidth() {
//        originalWidth = getWidth();
//        int newWidth = originalWidth - pnAccountInfo.getWidth();
//        setSize(newWidth, getHeight());
//        pnAccountInfo.setVisible(false);
//        setLocationRelativeTo(null);
//    }
//    private void extendForm(boolean extend) {
////        int currentWidth = getWidth();
//        int panelWidth = pnAccountInfo.getWidth();
//
//        if (extend) {
//            int newWidth = originalWidth + panelWidth;
//            setSize(newWidth, getHeight());
//            pnAccountInfo.setVisible(true);
//        } else {
//            int newWidth = originalWidth - panelWidth;
//            setSize(newWidth, getHeight());
//            pnAccountInfo.setVisible(false);
//        }
//
//        setLocationRelativeTo(null);
//    }
    private void runableThread(){
        Runnable frameGrabber = () -> {
                while (true) {
                    face.initializeCamera("Nhận diện", lblDisplayCapture);
                }
            };
            // Create a new thread for grabbing frames from the camera
            thread = new Thread(frameGrabber); 
            thread.setDaemon(true);  
            thread.start();   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcChooseImage = new javax.swing.JFileChooser();
        lblDisplayCapture = new javax.swing.JLabel();
        btnMoCamera = new javax.swing.JButton();
        btnNhanDien = new javax.swing.JButton();
        txtTiLe = new javax.swing.JTextField();
        lblDataFace = new javax.swing.JLabel();
        lblFaceCapture = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        btnMoCamera1 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        pnAccountInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbBirthDay = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbPanelBackGround = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblDisplayCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 26, 559, 424));

        btnMoCamera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMoCamera.setText("Mở camera");
        btnMoCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoCameraActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoCamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 47));

        btnNhanDien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNhanDien.setText("Nhận diện");
        btnNhanDien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanDienActionPerformed(evt);
            }
        });
        getContentPane().add(btnNhanDien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, 47));
        getContentPane().add(txtTiLe, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 286, 71, -1));
        getContentPane().add(lblDataFace, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 314, 284, 226));
        getContentPane().add(lblFaceCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 26, 284, 226));

        jLabel1.setText("Tỉ lệ giống: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 289, -1, -1));

        btnChonAnh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });
        getContentPane().add(btnChonAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 128, 47));

        btnMoCamera1.setText("Trở về");
        btnMoCamera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoCamera1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoCamera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 73, -1));

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 107, 47));

        pnAccountInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Thông tin tài khoản");
        pnAccountInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, 38));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Họ tên");
        pnAccountInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, -1));

        lbName.setBackground(new java.awt.Color(255, 255, 255));
        lbName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbName.setOpaque(true);
        pnAccountInfo.add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, 20));

        lbBirthDay.setBackground(new java.awt.Color(255, 255, 255));
        lbBirthDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbBirthDay.setOpaque(true);
        pnAccountInfo.add(lbBirthDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, 20));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Ngày sinh");
        pnAccountInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, -1));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("Giới tính");
        pnAccountInfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, -1));

        lbGender.setBackground(new java.awt.Color(255, 255, 255));
        lbGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbGender.setOpaque(true);
        pnAccountInfo.add(lbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 230, 20));

        lbPhone.setBackground(new java.awt.Color(255, 255, 255));
        lbPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPhone.setOpaque(true);
        pnAccountInfo.add(lbPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 230, 20));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 0));
        jLabel12.setText("SDT");
        pnAccountInfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 75, -1));

        lbEmail.setBackground(new java.awt.Color(255, 255, 255));
        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEmail.setOpaque(true);
        pnAccountInfo.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 230, 20));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 0));
        jLabel14.setText("Email");
        pnAccountInfo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 75, -1));

        lbAddress.setBackground(new java.awt.Color(255, 255, 255));
        lbAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAddress.setOpaque(true);
        pnAccountInfo.add(lbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 230, 20));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 0));
        jLabel16.setText("Địa chỉ");
        pnAccountInfo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 75, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.png"))); // NOI18N
        pnAccountInfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 70));

        lbPanelBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account_info.jpg"))); // NOI18N
        pnAccountInfo.add(lbPanelBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 570));

        getContentPane().add(pnAccountInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 370, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 890, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoCameraActionPerformed
        // TODO add your handling code here:
        if (face.isIsRecording()) {
            // Stop recording
            face.setIsRecording(false);
            btnMoCamera.setText("Record");
        } else {
            // Start recording
            face.setIsRecording(true);
            btnMoCamera.setText("Stop Recording");
        }
    }//GEN-LAST:event_btnMoCameraActionPerformed

    private void btnNhanDienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanDienActionPerformed
        // TODO add your handling code here:
        if(!face.isIsRecording() && imageChoose == null){
            JOptionPane.showMessageDialog(null, "Chưa chọn ảnh hoặc bật camera");
            return;
        }
        if(imageChoose != null){
            face.setImageChoose(imageChoose);   
            if(!face.isIsRecording())
                face.facialRecognition(imageChoose);
            
            imageChoose = null;
        }     
        
        if(!face.isCheck()){                       
            face.setCheck(true);   
        }
        
    }//GEN-LAST:event_btnNhanDienActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        // TODO add your handling code here:
        JFileChooser fcChooseImage = new JFileChooser();
        fcChooseImage.setVisible(true);
        fcChooseImage.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // Set file filter to allow only image files
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif");
        fcChooseImage.setFileFilter(imageFilter);

        if (fcChooseImage.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fcChooseImage.getSelectedFile();
                Path imagePath = selectedFile.toPath();
                byte[] imageBytes = Files.readAllBytes(imagePath);  
                byte[] faceImage = face.detctFace(imageBytes);
                if(faceImage != null){           
                    InputStream inputStream = new ByteArrayInputStream(faceImage );
                    BufferedImage imageBuffer1 = ImageIO.read(inputStream);
                    ImageIcon icon1 = new ImageIcon(imageBuffer1);
                    lblFaceCapture.setIcon(icon1);    
                    imageChoose = imageBytes;   
                }
                else{
                    JOptionPane.showMessageDialog(null, "Không tìm thấy khuôn mặt trong ảnh chọn");
                }
            } catch (HeadlessException | IOException ex) {
                JOptionPane.showConfirmDialog(null, ex);
            }
        }        
    }//GEN-LAST:event_btnChonAnhActionPerformed
    
    
   
    private void btnMoCamera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoCamera1ActionPerformed
        // TODO add your handling code here:
        face.setIsRecording(false);
        frmLogin open = new frmLogin();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMoCamera1ActionPerformed
    
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        face.setCheck(false);
        face.setIsRecording(false);
        frmRecognitionTest open = new frmRecognitionTest();
        open.setVisible(true );
        this.dispose();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecognitionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecognitionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecognitionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecognitionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecognitionTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnMoCamera;
    private javax.swing.JButton btnMoCamera1;
    private javax.swing.JButton btnNhanDien;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JFileChooser fcChooseImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbBirthDay;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPanelBackGround;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lblDataFace;
    private javax.swing.JLabel lblDisplayCapture;
    private javax.swing.JLabel lblFaceCapture;
    private javax.swing.JPanel pnAccountInfo;
    private javax.swing.JTextField txtTiLe;
    // End of variables declaration//GEN-END:variables
}
